// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: jm.proto

package jm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    []byte                 `protobuf:"bytes,1,opt,name=sessionKey" json:"sessionKey,omitempty"`
	Uin           *uint32                `protobuf:"varint,2,opt,name=uin" json:"uin,omitempty"`
	DeviceId      []byte                 `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
	ClientVersion *int32                 `protobuf:"varint,4,opt,name=clientVersion" json:"clientVersion,omitempty"`
	DeviceType    []byte                 `protobuf:"bytes,5,opt,name=deviceType" json:"deviceType,omitempty"`
	Scene         *uint32                `protobuf:"varint,6,opt,name=scene" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_jm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRequest) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *BaseRequest) GetUin() uint32 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

func (x *BaseRequest) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *BaseRequest) GetClientVersion() int32 {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return 0
}

func (x *BaseRequest) GetDeviceType() []byte {
	if x != nil {
		return x.DeviceType
	}
	return nil
}

func (x *BaseRequest) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

type BaseRequestPlus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 会话key base64字符串
	SessionKey    []byte  `protobuf:"bytes,1,opt,name=session_key,json=sessionKey" json:"session_key,omitempty"`
	Uin           *uint32 `protobuf:"varint,2,opt,name=uin" json:"uin,omitempty"`
	DeviceId      []byte  `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
	ClientVersion *int32  `protobuf:"varint,4,opt,name=clientVersion" json:"clientVersion,omitempty"`
	OsType        *string `protobuf:"bytes,5,opt,name=osType" json:"osType,omitempty"`
	Scene         *uint32 `protobuf:"varint,6,opt,name=scene" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequestPlus) Reset() {
	*x = BaseRequestPlus{}
	mi := &file_jm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequestPlus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequestPlus) ProtoMessage() {}

func (x *BaseRequestPlus) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequestPlus.ProtoReflect.Descriptor instead.
func (*BaseRequestPlus) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequestPlus) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *BaseRequestPlus) GetUin() uint32 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

func (x *BaseRequestPlus) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *BaseRequestPlus) GetClientVersion() int32 {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return 0
}

func (x *BaseRequestPlus) GetOsType() string {
	if x != nil && x.OsType != nil {
		return *x.OsType
	}
	return ""
}

func (x *BaseRequestPlus) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

type SKBuiltinStringT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	String_       *string                `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKBuiltinStringT) Reset() {
	*x = SKBuiltinStringT{}
	mi := &file_jm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKBuiltinStringT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinStringT) ProtoMessage() {}

func (x *SKBuiltinStringT) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinStringT.ProtoReflect.Descriptor instead.
func (*SKBuiltinStringT) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{2}
}

func (x *SKBuiltinStringT) GetString_() string {
	if x != nil && x.String_ != nil {
		return *x.String_
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *int32                 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	ErrMsg        *SKBuiltinStringT      `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_jm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{3}
}

func (x *BaseResponse) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *BaseResponse) GetErrMsg() *SKBuiltinStringT {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

type SKBuiltinString_S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ILen          *uint32                `protobuf:"varint,1,opt,name=iLen" json:"iLen,omitempty"`
	Buffer        *string                `protobuf:"bytes,2,opt,name=buffer" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKBuiltinString_S) Reset() {
	*x = SKBuiltinString_S{}
	mi := &file_jm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKBuiltinString_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinString_S) ProtoMessage() {}

func (x *SKBuiltinString_S) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinString_S.ProtoReflect.Descriptor instead.
func (*SKBuiltinString_S) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{4}
}

func (x *SKBuiltinString_S) GetILen() uint32 {
	if x != nil && x.ILen != nil {
		return *x.ILen
	}
	return 0
}

func (x *SKBuiltinString_S) GetBuffer() string {
	if x != nil && x.Buffer != nil {
		return *x.Buffer
	}
	return ""
}

type DecryptWxWorkChatRecordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptWxWorkChatRecordReq) Reset() {
	*x = DecryptWxWorkChatRecordReq{}
	mi := &file_jm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptWxWorkChatRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptWxWorkChatRecordReq) ProtoMessage() {}

func (x *DecryptWxWorkChatRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptWxWorkChatRecordReq.ProtoReflect.Descriptor instead.
func (*DecryptWxWorkChatRecordReq) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{5}
}

func (x *DecryptWxWorkChatRecordReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DecryptWxWorkChatRecordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResp      *BaseResponse          `protobuf:"bytes,1,opt,name=baseResp" json:"baseResp,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptWxWorkChatRecordResp) Reset() {
	*x = DecryptWxWorkChatRecordResp{}
	mi := &file_jm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptWxWorkChatRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptWxWorkChatRecordResp) ProtoMessage() {}

func (x *DecryptWxWorkChatRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptWxWorkChatRecordResp.ProtoReflect.Descriptor instead.
func (*DecryptWxWorkChatRecordResp) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{6}
}

func (x *DecryptWxWorkChatRecordResp) GetBaseResp() *BaseResponse {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *DecryptWxWorkChatRecordResp) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

type SKBuiltinString_ struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Len   *uint32                `protobuf:"varint,1,opt,name=len" json:"len,omitempty"`
	// base64字符串
	Buffer        []byte `protobuf:"bytes,2,opt,name=buffer" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKBuiltinString_) Reset() {
	*x = SKBuiltinString_{}
	mi := &file_jm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKBuiltinString_) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinString_) ProtoMessage() {}

func (x *SKBuiltinString_) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinString_.ProtoReflect.Descriptor instead.
func (*SKBuiltinString_) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{7}
}

func (x *SKBuiltinString_) GetLen() uint32 {
	if x != nil && x.Len != nil {
		return *x.Len
	}
	return 0
}

func (x *SKBuiltinString_) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type MassSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseRequest   *BaseRequest           `protobuf:"bytes,1,req,name=baseRequest" json:"baseRequest,omitempty"`
	ToList        *string                `protobuf:"bytes,2,opt,name=toList" json:"toList,omitempty"`
	ToListMd5     *string                `protobuf:"bytes,3,opt,name=toListMd5" json:"toListMd5,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,opt,name=clientId" json:"clientId,omitempty"`
	MsgType       *uint32                `protobuf:"varint,5,req,name=msgType" json:"msgType,omitempty"`
	MediaTime     *uint32                `protobuf:"varint,6,req,name=mediaTime" json:"mediaTime,omitempty"`
	DataBuffer    *SKBuiltinBufferT      `protobuf:"bytes,7,req,name=dataBuffer" json:"dataBuffer,omitempty"`
	DataStartPos  *uint32                `protobuf:"varint,8,req,name=dataStartPos" json:"dataStartPos,omitempty"`
	DataTotalLen  *uint32                `protobuf:"varint,9,req,name=dataTotalLen" json:"dataTotalLen,omitempty"`
	ThumbTotalLen *uint32                `protobuf:"varint,10,req,name=thumbTotalLen" json:"thumbTotalLen,omitempty"`
	ThumbStartPos *uint32                `protobuf:"varint,11,req,name=thumbStartPos" json:"thumbStartPos,omitempty"`
	ThumbData     *SKBuiltinBufferT      `protobuf:"bytes,12,req,name=thumbData" json:"thumbData,omitempty"`
	CameraType    *uint32                `protobuf:"varint,13,req,name=cameraType" json:"cameraType,omitempty"`
	VideoSource   *uint32                `protobuf:"varint,14,req,name=videoSource" json:"videoSource,omitempty"`
	ToListCount   *uint32                `protobuf:"varint,15,req,name=toListCount" json:"toListCount,omitempty"`
	IsSendAgain   *uint32                `protobuf:"varint,16,req,name=isSendAgain" json:"isSendAgain,omitempty"`
	CompressType  *uint32                `protobuf:"varint,17,opt,name=compressType" json:"compressType,omitempty"`
	VoiceFormat   *uint32                `protobuf:"varint,18,opt,name=voiceFormat" json:"voiceFormat,omitempty"`
	VideoUrl      *string                `protobuf:"bytes,19,opt,name=videoUrl" json:"videoUrl,omitempty"`
	ThumbUrl      *string                `protobuf:"bytes,20,opt,name=thumbUrl" json:"thumbUrl,omitempty"`
	ThumbWidth    *uint32                `protobuf:"varint,21,opt,name=thumbWidth" json:"thumbWidth,omitempty"`
	ThumbHeight   *uint32                `protobuf:"varint,22,opt,name=thumbHeight" json:"thumbHeight,omitempty"`
	ThumbAeskey   *string                `protobuf:"bytes,23,opt,name=thumbAeskey" json:"thumbAeskey,omitempty"`
	VideoAeskey   *string                `protobuf:"bytes,24,opt,name=videoAeskey" json:"videoAeskey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MassSendRequest) Reset() {
	*x = MassSendRequest{}
	mi := &file_jm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassSendRequest) ProtoMessage() {}

func (x *MassSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassSendRequest.ProtoReflect.Descriptor instead.
func (*MassSendRequest) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{8}
}

func (x *MassSendRequest) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *MassSendRequest) GetToList() string {
	if x != nil && x.ToList != nil {
		return *x.ToList
	}
	return ""
}

func (x *MassSendRequest) GetToListMd5() string {
	if x != nil && x.ToListMd5 != nil {
		return *x.ToListMd5
	}
	return ""
}

func (x *MassSendRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *MassSendRequest) GetMsgType() uint32 {
	if x != nil && x.MsgType != nil {
		return *x.MsgType
	}
	return 0
}

func (x *MassSendRequest) GetMediaTime() uint32 {
	if x != nil && x.MediaTime != nil {
		return *x.MediaTime
	}
	return 0
}

func (x *MassSendRequest) GetDataBuffer() *SKBuiltinBufferT {
	if x != nil {
		return x.DataBuffer
	}
	return nil
}

func (x *MassSendRequest) GetDataStartPos() uint32 {
	if x != nil && x.DataStartPos != nil {
		return *x.DataStartPos
	}
	return 0
}

func (x *MassSendRequest) GetDataTotalLen() uint32 {
	if x != nil && x.DataTotalLen != nil {
		return *x.DataTotalLen
	}
	return 0
}

func (x *MassSendRequest) GetThumbTotalLen() uint32 {
	if x != nil && x.ThumbTotalLen != nil {
		return *x.ThumbTotalLen
	}
	return 0
}

func (x *MassSendRequest) GetThumbStartPos() uint32 {
	if x != nil && x.ThumbStartPos != nil {
		return *x.ThumbStartPos
	}
	return 0
}

func (x *MassSendRequest) GetThumbData() *SKBuiltinBufferT {
	if x != nil {
		return x.ThumbData
	}
	return nil
}

func (x *MassSendRequest) GetCameraType() uint32 {
	if x != nil && x.CameraType != nil {
		return *x.CameraType
	}
	return 0
}

func (x *MassSendRequest) GetVideoSource() uint32 {
	if x != nil && x.VideoSource != nil {
		return *x.VideoSource
	}
	return 0
}

func (x *MassSendRequest) GetToListCount() uint32 {
	if x != nil && x.ToListCount != nil {
		return *x.ToListCount
	}
	return 0
}

func (x *MassSendRequest) GetIsSendAgain() uint32 {
	if x != nil && x.IsSendAgain != nil {
		return *x.IsSendAgain
	}
	return 0
}

func (x *MassSendRequest) GetCompressType() uint32 {
	if x != nil && x.CompressType != nil {
		return *x.CompressType
	}
	return 0
}

func (x *MassSendRequest) GetVoiceFormat() uint32 {
	if x != nil && x.VoiceFormat != nil {
		return *x.VoiceFormat
	}
	return 0
}

func (x *MassSendRequest) GetVideoUrl() string {
	if x != nil && x.VideoUrl != nil {
		return *x.VideoUrl
	}
	return ""
}

func (x *MassSendRequest) GetThumbUrl() string {
	if x != nil && x.ThumbUrl != nil {
		return *x.ThumbUrl
	}
	return ""
}

func (x *MassSendRequest) GetThumbWidth() uint32 {
	if x != nil && x.ThumbWidth != nil {
		return *x.ThumbWidth
	}
	return 0
}

func (x *MassSendRequest) GetThumbHeight() uint32 {
	if x != nil && x.ThumbHeight != nil {
		return *x.ThumbHeight
	}
	return 0
}

func (x *MassSendRequest) GetThumbAeskey() string {
	if x != nil && x.ThumbAeskey != nil {
		return *x.ThumbAeskey
	}
	return ""
}

func (x *MassSendRequest) GetVideoAeskey() string {
	if x != nil && x.VideoAeskey != nil {
		return *x.VideoAeskey
	}
	return ""
}

type SKBuiltinBufferT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ILen          *uint32                `protobuf:"varint,1,req,name=iLen" json:"iLen,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,2,opt,name=buffer" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKBuiltinBufferT) Reset() {
	*x = SKBuiltinBufferT{}
	mi := &file_jm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKBuiltinBufferT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinBufferT) ProtoMessage() {}

func (x *SKBuiltinBufferT) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinBufferT.ProtoReflect.Descriptor instead.
func (*SKBuiltinBufferT) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{9}
}

func (x *SKBuiltinBufferT) GetILen() uint32 {
	if x != nil && x.ILen != nil {
		return *x.ILen
	}
	return 0
}

func (x *SKBuiltinBufferT) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type MassSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *BaseResponse          `protobuf:"bytes,1,req,name=baseResponse" json:"baseResponse,omitempty"`
	DataStartPos  *uint32                `protobuf:"varint,2,req,name=dataStartPos" json:"dataStartPos,omitempty"`
	ThumbStartPos *uint32                `protobuf:"varint,3,req,name=thumbStartPos" json:"thumbStartPos,omitempty"`
	MaxSupport    *uint32                `protobuf:"varint,4,req,name=maxSupport" json:"maxSupport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MassSendResponse) Reset() {
	*x = MassSendResponse{}
	mi := &file_jm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MassSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassSendResponse) ProtoMessage() {}

func (x *MassSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassSendResponse.ProtoReflect.Descriptor instead.
func (*MassSendResponse) Descriptor() ([]byte, []int) {
	return file_jm_proto_rawDescGZIP(), []int{10}
}

func (x *MassSendResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *MassSendResponse) GetDataStartPos() uint32 {
	if x != nil && x.DataStartPos != nil {
		return *x.DataStartPos
	}
	return 0
}

func (x *MassSendResponse) GetThumbStartPos() uint32 {
	if x != nil && x.ThumbStartPos != nil {
		return *x.ThumbStartPos
	}
	return 0
}

func (x *MassSendResponse) GetMaxSupport() uint32 {
	if x != nil && x.MaxSupport != nil {
		return *x.MaxSupport
	}
	return 0
}

var File_jm_proto protoreflect.FileDescriptor

const file_jm_proto_rawDesc = "" +
	"\n" +
	"\bjm.proto\x12\x02jm\"\xb7\x01\n" +
	"\vBaseRequest\x12\x1e\n" +
	"\n" +
	"sessionKey\x18\x01 \x01(\fR\n" +
	"sessionKey\x12\x10\n" +
	"\x03uin\x18\x02 \x01(\rR\x03uin\x12\x1a\n" +
	"\bdeviceId\x18\x03 \x01(\fR\bdeviceId\x12$\n" +
	"\rclientVersion\x18\x04 \x01(\x05R\rclientVersion\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x05 \x01(\fR\n" +
	"deviceType\x12\x14\n" +
	"\x05scene\x18\x06 \x01(\rR\x05scene\"\xb4\x01\n" +
	"\x0fBaseRequestPlus\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\fR\n" +
	"sessionKey\x12\x10\n" +
	"\x03uin\x18\x02 \x01(\rR\x03uin\x12\x1a\n" +
	"\bdeviceId\x18\x03 \x01(\fR\bdeviceId\x12$\n" +
	"\rclientVersion\x18\x04 \x01(\x05R\rclientVersion\x12\x16\n" +
	"\x06osType\x18\x05 \x01(\tR\x06osType\x12\x14\n" +
	"\x05scene\x18\x06 \x01(\rR\x05scene\"+\n" +
	"\x11SKBuiltinString_t\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string\"O\n" +
	"\fBaseResponse\x12\x10\n" +
	"\x03ret\x18\x01 \x01(\x05R\x03ret\x12-\n" +
	"\x06errMsg\x18\x02 \x01(\v2\x15.jm.SKBuiltinString_tR\x06errMsg\"?\n" +
	"\x11SKBuiltinString_S\x12\x12\n" +
	"\x04iLen\x18\x01 \x01(\rR\x04iLen\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\tR\x06buffer\"6\n" +
	"\x1aDecryptWxWorkChatRecordReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"e\n" +
	"\x1bDecryptWxWorkChatRecordResp\x12,\n" +
	"\bbaseResp\x18\x01 \x01(\v2\x10.jm.BaseResponseR\bbaseResp\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"<\n" +
	"\x10SKBuiltinString_\x12\x10\n" +
	"\x03len\x18\x01 \x01(\rR\x03len\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\fR\x06buffer\"\xd8\x06\n" +
	"\x0fMassSendRequest\x121\n" +
	"\vbaseRequest\x18\x01 \x02(\v2\x0f.jm.BaseRequestR\vbaseRequest\x12\x16\n" +
	"\x06toList\x18\x02 \x01(\tR\x06toList\x12\x1c\n" +
	"\ttoListMd5\x18\x03 \x01(\tR\ttoListMd5\x12\x1a\n" +
	"\bclientId\x18\x04 \x01(\tR\bclientId\x12\x18\n" +
	"\amsgType\x18\x05 \x02(\rR\amsgType\x12\x1c\n" +
	"\tmediaTime\x18\x06 \x02(\rR\tmediaTime\x125\n" +
	"\n" +
	"dataBuffer\x18\a \x02(\v2\x15.jm.SKBuiltinBuffer_tR\n" +
	"dataBuffer\x12\"\n" +
	"\fdataStartPos\x18\b \x02(\rR\fdataStartPos\x12\"\n" +
	"\fdataTotalLen\x18\t \x02(\rR\fdataTotalLen\x12$\n" +
	"\rthumbTotalLen\x18\n" +
	" \x02(\rR\rthumbTotalLen\x12$\n" +
	"\rthumbStartPos\x18\v \x02(\rR\rthumbStartPos\x123\n" +
	"\tthumbData\x18\f \x02(\v2\x15.jm.SKBuiltinBuffer_tR\tthumbData\x12\x1e\n" +
	"\n" +
	"cameraType\x18\r \x02(\rR\n" +
	"cameraType\x12 \n" +
	"\vvideoSource\x18\x0e \x02(\rR\vvideoSource\x12 \n" +
	"\vtoListCount\x18\x0f \x02(\rR\vtoListCount\x12 \n" +
	"\visSendAgain\x18\x10 \x02(\rR\visSendAgain\x12\"\n" +
	"\fcompressType\x18\x11 \x01(\rR\fcompressType\x12 \n" +
	"\vvoiceFormat\x18\x12 \x01(\rR\vvoiceFormat\x12\x1a\n" +
	"\bvideoUrl\x18\x13 \x01(\tR\bvideoUrl\x12\x1a\n" +
	"\bthumbUrl\x18\x14 \x01(\tR\bthumbUrl\x12\x1e\n" +
	"\n" +
	"thumbWidth\x18\x15 \x01(\rR\n" +
	"thumbWidth\x12 \n" +
	"\vthumbHeight\x18\x16 \x01(\rR\vthumbHeight\x12 \n" +
	"\vthumbAeskey\x18\x17 \x01(\tR\vthumbAeskey\x12 \n" +
	"\vvideoAeskey\x18\x18 \x01(\tR\vvideoAeskey\"?\n" +
	"\x11SKBuiltinBuffer_t\x12\x12\n" +
	"\x04iLen\x18\x01 \x02(\rR\x04iLen\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\fR\x06buffer\"\xb2\x01\n" +
	"\x10MassSendResponse\x124\n" +
	"\fbaseResponse\x18\x01 \x02(\v2\x10.jm.BaseResponseR\fbaseResponse\x12\"\n" +
	"\fdataStartPos\x18\x02 \x02(\rR\fdataStartPos\x12$\n" +
	"\rthumbStartPos\x18\x03 \x02(\rR\rthumbStartPos\x12\x1e\n" +
	"\n" +
	"maxSupport\x18\x04 \x02(\rR\n" +
	"maxSupportB\x06Z\x04/;jm"

var (
	file_jm_proto_rawDescOnce sync.Once
	file_jm_proto_rawDescData []byte
)

func file_jm_proto_rawDescGZIP() []byte {
	file_jm_proto_rawDescOnce.Do(func() {
		file_jm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jm_proto_rawDesc), len(file_jm_proto_rawDesc)))
	})
	return file_jm_proto_rawDescData
}

var file_jm_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_jm_proto_goTypes = []any{
	(*BaseRequest)(nil),                 // 0: jm.BaseRequest
	(*BaseRequestPlus)(nil),             // 1: jm.BaseRequestPlus
	(*SKBuiltinStringT)(nil),            // 2: jm.SKBuiltinString_t
	(*BaseResponse)(nil),                // 3: jm.BaseResponse
	(*SKBuiltinString_S)(nil),           // 4: jm.SKBuiltinString_S
	(*DecryptWxWorkChatRecordReq)(nil),  // 5: jm.DecryptWxWorkChatRecordReq
	(*DecryptWxWorkChatRecordResp)(nil), // 6: jm.DecryptWxWorkChatRecordResp
	(*SKBuiltinString_)(nil),            // 7: jm.SKBuiltinString_
	(*MassSendRequest)(nil),             // 8: jm.MassSendRequest
	(*SKBuiltinBufferT)(nil),            // 9: jm.SKBuiltinBuffer_t
	(*MassSendResponse)(nil),            // 10: jm.MassSendResponse
}
var file_jm_proto_depIdxs = []int32{
	2, // 0: jm.BaseResponse.errMsg:type_name -> jm.SKBuiltinString_t
	3, // 1: jm.DecryptWxWorkChatRecordResp.baseResp:type_name -> jm.BaseResponse
	0, // 2: jm.MassSendRequest.baseRequest:type_name -> jm.BaseRequest
	9, // 3: jm.MassSendRequest.dataBuffer:type_name -> jm.SKBuiltinBuffer_t
	9, // 4: jm.MassSendRequest.thumbData:type_name -> jm.SKBuiltinBuffer_t
	3, // 5: jm.MassSendResponse.baseResponse:type_name -> jm.BaseResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_jm_proto_init() }
func file_jm_proto_init() {
	if File_jm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jm_proto_rawDesc), len(file_jm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jm_proto_goTypes,
		DependencyIndexes: file_jm_proto_depIdxs,
		MessageInfos:      file_jm_proto_msgTypes,
	}.Build()
	File_jm_proto = out.File
	file_jm_proto_goTypes = nil
	file_jm_proto_depIdxs = nil
}
