// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: mw.proto

package mw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SKBuiltinBufferWinT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ILen          *uint32                `protobuf:"varint,1,opt,name=iLen" json:"iLen,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,2,opt,name=buffer" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKBuiltinBufferWinT) Reset() {
	*x = SKBuiltinBufferWinT{}
	mi := &file_mw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKBuiltinBufferWinT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinBufferWinT) ProtoMessage() {}

func (x *SKBuiltinBufferWinT) ProtoReflect() protoreflect.Message {
	mi := &file_mw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinBufferWinT.ProtoReflect.Descriptor instead.
func (*SKBuiltinBufferWinT) Descriptor() ([]byte, []int) {
	return file_mw_proto_rawDescGZIP(), []int{0}
}

func (x *SKBuiltinBufferWinT) GetILen() uint32 {
	if x != nil && x.ILen != nil {
		return *x.ILen
	}
	return 0
}

func (x *SKBuiltinBufferWinT) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type AcctSectResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserName         *string                `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	NickName         *string                `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	BindUin          *uint32                `protobuf:"varint,3,opt,name=bindUin" json:"bindUin,omitempty"`
	BindEmail        *string                `protobuf:"bytes,4,opt,name=bindEmail" json:"bindEmail,omitempty"`
	BindMobile       *string                `protobuf:"bytes,5,opt,name=bindMobile" json:"bindMobile,omitempty"`
	Alias            *string                `protobuf:"bytes,6,opt,name=alias" json:"alias,omitempty"`
	Status           *uint32                `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
	PluginFlag       *uint32                `protobuf:"varint,9,opt,name=pluginFlag" json:"pluginFlag,omitempty"`
	RegType          *uint32                `protobuf:"varint,10,opt,name=regType" json:"regType,omitempty"`
	DeviceInfoXml    *string                `protobuf:"bytes,11,opt,name=deviceInfoXml" json:"deviceInfoXml,omitempty"`
	SafeDevice       *uint32                `protobuf:"varint,12,opt,name=safeDevice" json:"safeDevice,omitempty"`
	OfficialUserName *string                `protobuf:"bytes,13,opt,name=officialUserName" json:"officialUserName,omitempty"`
	OfficialNickName *string                `protobuf:"bytes,14,opt,name=officialNickName" json:"officialNickName,omitempty"`
	PushMailStatus   *uint32                `protobuf:"varint,15,opt,name=pushMailStatus" json:"pushMailStatus,omitempty"`
	Fsurl            *string                `protobuf:"bytes,16,opt,name=fsurl" json:"fsurl,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcctSectResp) Reset() {
	*x = AcctSectResp{}
	mi := &file_mw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcctSectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctSectResp) ProtoMessage() {}

func (x *AcctSectResp) ProtoReflect() protoreflect.Message {
	mi := &file_mw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctSectResp.ProtoReflect.Descriptor instead.
func (*AcctSectResp) Descriptor() ([]byte, []int) {
	return file_mw_proto_rawDescGZIP(), []int{1}
}

func (x *AcctSectResp) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *AcctSectResp) GetNickName() string {
	if x != nil && x.NickName != nil {
		return *x.NickName
	}
	return ""
}

func (x *AcctSectResp) GetBindUin() uint32 {
	if x != nil && x.BindUin != nil {
		return *x.BindUin
	}
	return 0
}

func (x *AcctSectResp) GetBindEmail() string {
	if x != nil && x.BindEmail != nil {
		return *x.BindEmail
	}
	return ""
}

func (x *AcctSectResp) GetBindMobile() string {
	if x != nil && x.BindMobile != nil {
		return *x.BindMobile
	}
	return ""
}

func (x *AcctSectResp) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *AcctSectResp) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *AcctSectResp) GetPluginFlag() uint32 {
	if x != nil && x.PluginFlag != nil {
		return *x.PluginFlag
	}
	return 0
}

func (x *AcctSectResp) GetRegType() uint32 {
	if x != nil && x.RegType != nil {
		return *x.RegType
	}
	return 0
}

func (x *AcctSectResp) GetDeviceInfoXml() string {
	if x != nil && x.DeviceInfoXml != nil {
		return *x.DeviceInfoXml
	}
	return ""
}

func (x *AcctSectResp) GetSafeDevice() uint32 {
	if x != nil && x.SafeDevice != nil {
		return *x.SafeDevice
	}
	return 0
}

func (x *AcctSectResp) GetOfficialUserName() string {
	if x != nil && x.OfficialUserName != nil {
		return *x.OfficialUserName
	}
	return ""
}

func (x *AcctSectResp) GetOfficialNickName() string {
	if x != nil && x.OfficialNickName != nil {
		return *x.OfficialNickName
	}
	return ""
}

func (x *AcctSectResp) GetPushMailStatus() uint32 {
	if x != nil && x.PushMailStatus != nil {
		return *x.PushMailStatus
	}
	return 0
}

func (x *AcctSectResp) GetFsurl() string {
	if x != nil && x.Fsurl != nil {
		return *x.Fsurl
	}
	return ""
}

type BaseRequestWin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    []byte                 `protobuf:"bytes,1,opt,name=sessionKey" json:"sessionKey,omitempty"`
	Uin           *uint32                `protobuf:"varint,2,opt,name=uin" json:"uin,omitempty"`
	DeviceId      []byte                 `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
	ClientVersion *uint32                `protobuf:"varint,4,opt,name=clientVersion" json:"clientVersion,omitempty"`
	DeviceType    []byte                 `protobuf:"bytes,5,opt,name=deviceType" json:"deviceType,omitempty"`
	Scene         *uint32                `protobuf:"varint,6,opt,name=scene" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequestWin) Reset() {
	*x = BaseRequestWin{}
	mi := &file_mw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequestWin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequestWin) ProtoMessage() {}

func (x *BaseRequestWin) ProtoReflect() protoreflect.Message {
	mi := &file_mw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequestWin.ProtoReflect.Descriptor instead.
func (*BaseRequestWin) Descriptor() ([]byte, []int) {
	return file_mw_proto_rawDescGZIP(), []int{2}
}

func (x *BaseRequestWin) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *BaseRequestWin) GetUin() uint32 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

func (x *BaseRequestWin) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *BaseRequestWin) GetClientVersion() uint32 {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return 0
}

func (x *BaseRequestWin) GetDeviceType() []byte {
	if x != nil {
		return x.DeviceType
	}
	return nil
}

func (x *BaseRequestWin) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

type GetLoginQRCodeRequestWin struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseRequest      *BaseRequestWin        `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	RandomEncryKey   *SKBuiltinBufferWinT   `protobuf:"bytes,2,opt,name=randomEncryKey" json:"randomEncryKey,omitempty"`
	Opcode           *uint32                `protobuf:"varint,3,opt,name=opcode" json:"opcode,omitempty"`
	DeviceName       *string                `protobuf:"bytes,4,opt,name=deviceName" json:"deviceName,omitempty"`
	UserName         *string                `protobuf:"bytes,5,opt,name=userName" json:"userName,omitempty"`
	ExtDevLoginType  *uint32                `protobuf:"varint,6,opt,name=extDevLoginType" json:"extDevLoginType,omitempty"`
	HardwareExtra    *string                `protobuf:"bytes,7,opt,name=hardwareExtra" json:"hardwareExtra,omitempty"`
	SoftType         *string                `protobuf:"bytes,8,opt,name=softType" json:"softType,omitempty"`
	MsgContextPubKey *SKBuiltinBufferWinT   `protobuf:"bytes,9,opt,name=msgContextPubKey" json:"msgContextPubKey,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetLoginQRCodeRequestWin) Reset() {
	*x = GetLoginQRCodeRequestWin{}
	mi := &file_mw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginQRCodeRequestWin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginQRCodeRequestWin) ProtoMessage() {}

func (x *GetLoginQRCodeRequestWin) ProtoReflect() protoreflect.Message {
	mi := &file_mw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginQRCodeRequestWin.ProtoReflect.Descriptor instead.
func (*GetLoginQRCodeRequestWin) Descriptor() ([]byte, []int) {
	return file_mw_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoginQRCodeRequestWin) GetBaseRequest() *BaseRequestWin {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *GetLoginQRCodeRequestWin) GetRandomEncryKey() *SKBuiltinBufferWinT {
	if x != nil {
		return x.RandomEncryKey
	}
	return nil
}

func (x *GetLoginQRCodeRequestWin) GetOpcode() uint32 {
	if x != nil && x.Opcode != nil {
		return *x.Opcode
	}
	return 0
}

func (x *GetLoginQRCodeRequestWin) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *GetLoginQRCodeRequestWin) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *GetLoginQRCodeRequestWin) GetExtDevLoginType() uint32 {
	if x != nil && x.ExtDevLoginType != nil {
		return *x.ExtDevLoginType
	}
	return 0
}

func (x *GetLoginQRCodeRequestWin) GetHardwareExtra() string {
	if x != nil && x.HardwareExtra != nil {
		return *x.HardwareExtra
	}
	return ""
}

func (x *GetLoginQRCodeRequestWin) GetSoftType() string {
	if x != nil && x.SoftType != nil {
		return *x.SoftType
	}
	return ""
}

func (x *GetLoginQRCodeRequestWin) GetMsgContextPubKey() *SKBuiltinBufferWinT {
	if x != nil {
		return x.MsgContextPubKey
	}
	return nil
}

type FPFresh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseRequest   *BaseRequest           `protobuf:"bytes,1,opt,name=baseRequest" json:"baseRequest,omitempty"`
	SessKey       []byte                 `protobuf:"bytes,2,opt,name=SessKey" json:"SessKey,omitempty"`
	Ztdata        *ZTData                `protobuf:"bytes,3,opt,name=Ztdata" json:"Ztdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FPFresh) Reset() {
	*x = FPFresh{}
	mi := &file_mw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FPFresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FPFresh) ProtoMessage() {}

func (x *FPFresh) ProtoReflect() protoreflect.Message {
	mi := &file_mw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FPFresh.ProtoReflect.Descriptor instead.
func (*FPFresh) Descriptor() ([]byte, []int) {
	return file_mw_proto_rawDescGZIP(), []int{4}
}

func (x *FPFresh) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *FPFresh) GetSessKey() []byte {
	if x != nil {
		return x.SessKey
	}
	return nil
}

func (x *FPFresh) GetZtdata() *ZTData {
	if x != nil {
		return x.Ztdata
	}
	return nil
}

type ZTData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *string                `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Encrypted     *uint32                `protobuf:"varint,2,opt,name=Encrypted" json:"Encrypted,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data" json:"Data,omitempty"`
	TimeStamp     *uint32                `protobuf:"varint,4,opt,name=TimeStamp" json:"TimeStamp,omitempty"`
	Optype        *uint32                `protobuf:"varint,5,opt,name=Optype" json:"Optype,omitempty"`
	Uin           *uint32                `protobuf:"varint,6,opt,name=Uin" json:"Uin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZTData) Reset() {
	*x = ZTData{}
	mi := &file_mw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZTData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZTData) ProtoMessage() {}

func (x *ZTData) ProtoReflect() protoreflect.Message {
	mi := &file_mw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZTData.ProtoReflect.Descriptor instead.
func (*ZTData) Descriptor() ([]byte, []int) {
	return file_mw_proto_rawDescGZIP(), []int{5}
}

func (x *ZTData) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *ZTData) GetEncrypted() uint32 {
	if x != nil && x.Encrypted != nil {
		return *x.Encrypted
	}
	return 0
}

func (x *ZTData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ZTData) GetTimeStamp() uint32 {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return 0
}

func (x *ZTData) GetOptype() uint32 {
	if x != nil && x.Optype != nil {
		return *x.Optype
	}
	return 0
}

func (x *ZTData) GetUin() uint32 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    []byte                 `protobuf:"bytes,1,opt,name=sessionKey" json:"sessionKey,omitempty"`
	Uin           *uint32                `protobuf:"varint,2,opt,name=uin" json:"uin,omitempty"`
	DeviceId      []byte                 `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
	ClientVersion *uint32                `protobuf:"varint,4,opt,name=clientVersion" json:"clientVersion,omitempty"`
	DeviceType    []byte                 `protobuf:"bytes,5,opt,name=deviceType" json:"deviceType,omitempty"`
	Scene         *uint32                `protobuf:"varint,6,opt,name=scene" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_mw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_mw_proto_rawDescGZIP(), []int{6}
}

func (x *BaseRequest) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *BaseRequest) GetUin() uint32 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

func (x *BaseRequest) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *BaseRequest) GetClientVersion() uint32 {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return 0
}

func (x *BaseRequest) GetDeviceType() []byte {
	if x != nil {
		return x.DeviceType
	}
	return nil
}

func (x *BaseRequest) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

var File_mw_proto protoreflect.FileDescriptor

const file_mw_proto_rawDesc = "" +
	"\n" +
	"\bmw.proto\x12\x02mw\"B\n" +
	"\x14SKBuiltinBufferWin_t\x12\x12\n" +
	"\x04iLen\x18\x01 \x01(\rR\x04iLen\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\fR\x06buffer\"\xe2\x03\n" +
	"\fAcctSectResp\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\x12\x18\n" +
	"\abindUin\x18\x03 \x01(\rR\abindUin\x12\x1c\n" +
	"\tbindEmail\x18\x04 \x01(\tR\tbindEmail\x12\x1e\n" +
	"\n" +
	"bindMobile\x18\x05 \x01(\tR\n" +
	"bindMobile\x12\x14\n" +
	"\x05alias\x18\x06 \x01(\tR\x05alias\x12\x16\n" +
	"\x06status\x18\b \x01(\rR\x06status\x12\x1e\n" +
	"\n" +
	"pluginFlag\x18\t \x01(\rR\n" +
	"pluginFlag\x12\x18\n" +
	"\aregType\x18\n" +
	" \x01(\rR\aregType\x12$\n" +
	"\rdeviceInfoXml\x18\v \x01(\tR\rdeviceInfoXml\x12\x1e\n" +
	"\n" +
	"safeDevice\x18\f \x01(\rR\n" +
	"safeDevice\x12*\n" +
	"\x10officialUserName\x18\r \x01(\tR\x10officialUserName\x12*\n" +
	"\x10officialNickName\x18\x0e \x01(\tR\x10officialNickName\x12&\n" +
	"\x0epushMailStatus\x18\x0f \x01(\rR\x0epushMailStatus\x12\x14\n" +
	"\x05fsurl\x18\x10 \x01(\tR\x05fsurl\"\xba\x01\n" +
	"\x0eBaseRequestWin\x12\x1e\n" +
	"\n" +
	"sessionKey\x18\x01 \x01(\fR\n" +
	"sessionKey\x12\x10\n" +
	"\x03uin\x18\x02 \x01(\rR\x03uin\x12\x1a\n" +
	"\bdeviceId\x18\x03 \x01(\fR\bdeviceId\x12$\n" +
	"\rclientVersion\x18\x04 \x01(\rR\rclientVersion\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x05 \x01(\fR\n" +
	"deviceType\x12\x14\n" +
	"\x05scene\x18\x06 \x01(\rR\x05scene\"\x98\x03\n" +
	"\x18GetLoginQRCodeRequestWin\x124\n" +
	"\vbaseRequest\x18\x01 \x01(\v2\x12.mw.BaseRequestWinR\vbaseRequest\x12@\n" +
	"\x0erandomEncryKey\x18\x02 \x01(\v2\x18.mw.SKBuiltinBufferWin_tR\x0erandomEncryKey\x12\x16\n" +
	"\x06opcode\x18\x03 \x01(\rR\x06opcode\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1a\n" +
	"\buserName\x18\x05 \x01(\tR\buserName\x12(\n" +
	"\x0fextDevLoginType\x18\x06 \x01(\rR\x0fextDevLoginType\x12$\n" +
	"\rhardwareExtra\x18\a \x01(\tR\rhardwareExtra\x12\x1a\n" +
	"\bsoftType\x18\b \x01(\tR\bsoftType\x12D\n" +
	"\x10msgContextPubKey\x18\t \x01(\v2\x18.mw.SKBuiltinBufferWin_tR\x10msgContextPubKey\"z\n" +
	"\aFPFresh\x121\n" +
	"\vbaseRequest\x18\x01 \x01(\v2\x0f.mw.BaseRequestR\vbaseRequest\x12\x18\n" +
	"\aSessKey\x18\x02 \x01(\fR\aSessKey\x12\"\n" +
	"\x06Ztdata\x18\x03 \x01(\v2\n" +
	".mw.ZTDataR\x06Ztdata\"\x9c\x01\n" +
	"\x06ZTData\x12\x18\n" +
	"\aVersion\x18\x01 \x01(\tR\aVersion\x12\x1c\n" +
	"\tEncrypted\x18\x02 \x01(\rR\tEncrypted\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x1c\n" +
	"\tTimeStamp\x18\x04 \x01(\rR\tTimeStamp\x12\x16\n" +
	"\x06Optype\x18\x05 \x01(\rR\x06Optype\x12\x10\n" +
	"\x03Uin\x18\x06 \x01(\rR\x03Uin\"\xb7\x01\n" +
	"\vBaseRequest\x12\x1e\n" +
	"\n" +
	"sessionKey\x18\x01 \x01(\fR\n" +
	"sessionKey\x12\x10\n" +
	"\x03uin\x18\x02 \x01(\rR\x03uin\x12\x1a\n" +
	"\bdeviceId\x18\x03 \x01(\fR\bdeviceId\x12$\n" +
	"\rclientVersion\x18\x04 \x01(\rR\rclientVersion\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x05 \x01(\fR\n" +
	"deviceType\x12\x14\n" +
	"\x05scene\x18\x06 \x01(\rR\x05sceneB\x06Z\x04/;mw"

var (
	file_mw_proto_rawDescOnce sync.Once
	file_mw_proto_rawDescData []byte
)

func file_mw_proto_rawDescGZIP() []byte {
	file_mw_proto_rawDescOnce.Do(func() {
		file_mw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mw_proto_rawDesc), len(file_mw_proto_rawDesc)))
	})
	return file_mw_proto_rawDescData
}

var file_mw_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mw_proto_goTypes = []any{
	(*SKBuiltinBufferWinT)(nil),      // 0: mw.SKBuiltinBufferWin_t
	(*AcctSectResp)(nil),             // 1: mw.AcctSectResp
	(*BaseRequestWin)(nil),           // 2: mw.BaseRequestWin
	(*GetLoginQRCodeRequestWin)(nil), // 3: mw.GetLoginQRCodeRequestWin
	(*FPFresh)(nil),                  // 4: mw.FPFresh
	(*ZTData)(nil),                   // 5: mw.ZTData
	(*BaseRequest)(nil),              // 6: mw.BaseRequest
}
var file_mw_proto_depIdxs = []int32{
	2, // 0: mw.GetLoginQRCodeRequestWin.baseRequest:type_name -> mw.BaseRequestWin
	0, // 1: mw.GetLoginQRCodeRequestWin.randomEncryKey:type_name -> mw.SKBuiltinBufferWin_t
	0, // 2: mw.GetLoginQRCodeRequestWin.msgContextPubKey:type_name -> mw.SKBuiltinBufferWin_t
	6, // 3: mw.FPFresh.baseRequest:type_name -> mw.BaseRequest
	5, // 4: mw.FPFresh.Ztdata:type_name -> mw.ZTData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mw_proto_init() }
func file_mw_proto_init() {
	if File_mw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mw_proto_rawDesc), len(file_mw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mw_proto_goTypes,
		DependencyIndexes: file_mw_proto_depIdxs,
		MessageInfos:      file_mw_proto_msgTypes,
	}.Build()
	File_mw_proto = out.File
	file_mw_proto_goTypes = nil
	file_mw_proto_depIdxs = nil
}
