// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: payparams.proto

package mm2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey    []byte  `protobuf:"bytes,1,opt,name=sessionKey" json:"sessionKey,omitempty"`
	Uin           *uint32 `protobuf:"varint,2,opt,name=uin" json:"uin,omitempty"`
	DeviceId      []byte  `protobuf:"bytes,3,opt,name=deviceId" json:"deviceId,omitempty"`
	ClientVersion *int32  `protobuf:"varint,4,opt,name=clientVersion" json:"clientVersion,omitempty"`
	DeviceType    []byte  `protobuf:"bytes,5,opt,name=deviceType" json:"deviceType,omitempty"`
	Scene         *uint32 `protobuf:"varint,6,opt,name=scene" json:"scene,omitempty"`
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRequest) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *BaseRequest) GetUin() uint32 {
	if x != nil && x.Uin != nil {
		return *x.Uin
	}
	return 0
}

func (x *BaseRequest) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *BaseRequest) GetClientVersion() int32 {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return 0
}

func (x *BaseRequest) GetDeviceType() []byte {
	if x != nil {
		return x.DeviceType
	}
	return nil
}

func (x *BaseRequest) GetScene() uint32 {
	if x != nil && x.Scene != nil {
		return *x.Scene
	}
	return 0
}

type SKBuiltinStringT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"` // 假设SKBuiltinStringT是为了兼容性保留，实际当作普通字符串处理
}

func (x *SKBuiltinStringT) Reset() {
	*x = SKBuiltinStringT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKBuiltinStringT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinStringT) ProtoMessage() {}

func (x *SKBuiltinStringT) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinStringT.ProtoReflect.Descriptor instead.
func (*SKBuiltinStringT) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{1}
}

func (x *SKBuiltinStringT) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type BaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    *int32            `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	ErrMsg *SKBuiltinStringT `protobuf:"bytes,2,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResponse) GetRet() int32 {
	if x != nil && x.Ret != nil {
		return *x.Ret
	}
	return 0
}

func (x *BaseResponse) GetErrMsg() *SKBuiltinStringT {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

type GetOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,opt,name=BaseRequest" json:"BaseRequest,omitempty"`
	Tmp2        *uint64      `protobuf:"varint,2,opt,name=tmp2" json:"tmp2,omitempty"`
	Tmp3        *string      `protobuf:"bytes,3,opt,name=tmp3" json:"tmp3,omitempty"`
	Tmp4        *Tmp4        `protobuf:"bytes,4,opt,name=tmp4" json:"tmp4,omitempty"`
}

func (x *GetOrder) Reset() {
	*x = GetOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrder) ProtoMessage() {}

func (x *GetOrder) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrder.ProtoReflect.Descriptor instead.
func (*GetOrder) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrder) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *GetOrder) GetTmp2() uint64 {
	if x != nil && x.Tmp2 != nil {
		return *x.Tmp2
	}
	return 0
}

func (x *GetOrder) GetTmp3() string {
	if x != nil && x.Tmp3 != nil {
		return *x.Tmp3
	}
	return ""
}

func (x *GetOrder) GetTmp4() *Tmp4 {
	if x != nil {
		return x.Tmp4
	}
	return nil
}

type Tmp4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tmp4_1 *Tmp4_1 `protobuf:"bytes,1,opt,name=Tmp4_1,json=Tmp41" json:"Tmp4_1,omitempty"`
	Tmp4_2 *string `protobuf:"bytes,2,opt,name=tmp4_2,json=tmp42" json:"tmp4_2,omitempty"`
	Tmp4_3 *uint64 `protobuf:"varint,3,opt,name=tmp4_3,json=tmp43" json:"tmp4_3,omitempty"`
}

func (x *Tmp4) Reset() {
	*x = Tmp4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tmp4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tmp4) ProtoMessage() {}

func (x *Tmp4) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tmp4.ProtoReflect.Descriptor instead.
func (*Tmp4) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{4}
}

func (x *Tmp4) GetTmp4_1() *Tmp4_1 {
	if x != nil {
		return x.Tmp4_1
	}
	return nil
}

func (x *Tmp4) GetTmp4_2() string {
	if x != nil && x.Tmp4_2 != nil {
		return *x.Tmp4_2
	}
	return ""
}

func (x *Tmp4) GetTmp4_3() uint64 {
	if x != nil && x.Tmp4_3 != nil {
		return *x.Tmp4_3
	}
	return 0
}

type Tmp4_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,opt,name=BaseRequest" json:"BaseRequest,omitempty"`
	Payparams   *Payparams   `protobuf:"bytes,3,opt,name=payparams" json:"payparams,omitempty"`
}

func (x *Tmp4_1) Reset() {
	*x = Tmp4_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tmp4_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tmp4_1) ProtoMessage() {}

func (x *Tmp4_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tmp4_1.ProtoReflect.Descriptor instead.
func (*Tmp4_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{5}
}

func (x *Tmp4_1) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *Tmp4_1) GetPayparams() *Payparams {
	if x != nil {
		return x.Payparams
	}
	return nil
}

type Payparams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     *string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	NonceStr  *string `protobuf:"bytes,4,opt,name=nonceStr" json:"nonceStr,omitempty"`
	TimeStamp *string `protobuf:"bytes,5,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Package_  *string `protobuf:"bytes,6,opt,name=package_,json=package" json:"package_,omitempty"` // 使用"package_"以避免与保留字冲突
	PaySign   *string `protobuf:"bytes,7,opt,name=paySign" json:"paySign,omitempty"`
	SignType  *string `protobuf:"bytes,8,opt,name=signType" json:"signType,omitempty"`
}

func (x *Payparams) Reset() {
	*x = Payparams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payparams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payparams) ProtoMessage() {}

func (x *Payparams) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payparams.ProtoReflect.Descriptor instead.
func (*Payparams) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{6}
}

func (x *Payparams) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *Payparams) GetNonceStr() string {
	if x != nil && x.NonceStr != nil {
		return *x.NonceStr
	}
	return ""
}

func (x *Payparams) GetTimeStamp() string {
	if x != nil && x.TimeStamp != nil {
		return *x.TimeStamp
	}
	return ""
}

func (x *Payparams) GetPackage_() string {
	if x != nil && x.Package_ != nil {
		return *x.Package_
	}
	return ""
}

func (x *Payparams) GetPaySign() string {
	if x != nil && x.PaySign != nil {
		return *x.PaySign
	}
	return ""
}

func (x *Payparams) GetSignType() string {
	if x != nil && x.SignType != nil {
		return *x.SignType
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse       *BaseResponse       `protobuf:"bytes,1,opt,name=BaseResponse" json:"BaseResponse,omitempty"`
	GetOrderResponse_3 *GetOrderResponse_3 `protobuf:"bytes,3,opt,name=GetOrderResponse_3,json=GetOrderResponse3" json:"GetOrderResponse_3,omitempty"`
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetOrderResponse) GetGetOrderResponse_3() *GetOrderResponse_3 {
	if x != nil {
		return x.GetOrderResponse_3
	}
	return nil
}

type GetOrderResponse_3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1 *GetOrderResponse_3_1 `protobuf:"bytes,1,opt,name=GetOrderResponse_3_1,json=GetOrderResponse31" json:"GetOrderResponse_3_1,omitempty"`
}

func (x *GetOrderResponse_3) Reset() {
	*x = GetOrderResponse_3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3) ProtoMessage() {}

func (x *GetOrderResponse_3) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderResponse_3) GetGetOrderResponse_3_1() *GetOrderResponse_3_1 {
	if x != nil {
		return x.GetOrderResponse_3_1
	}
	return nil
}

type GetOrderResponse_3_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_2  *GetOrderResponse_3_1_2  `protobuf:"bytes,2,opt,name=GetOrderResponse_3_1_2,json=GetOrderResponse312" json:"GetOrderResponse_3_1_2,omitempty"`
	GetOrderResponse_3_1_6  *GetOrderResponse_3_1_6  `protobuf:"bytes,6,opt,name=GetOrderResponse_3_1_6,json=GetOrderResponse316" json:"GetOrderResponse_3_1_6,omitempty"`
	GetOrderResponse_3_1_15 *GetOrderResponse_3_1_15 `protobuf:"bytes,15,opt,name=GetOrderResponse_3_1_15,json=GetOrderResponse3115" json:"GetOrderResponse_3_1_15,omitempty"`
}

func (x *GetOrderResponse_3_1) Reset() {
	*x = GetOrderResponse_3_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1) ProtoMessage() {}

func (x *GetOrderResponse_3_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderResponse_3_1) GetGetOrderResponse_3_1_2() *GetOrderResponse_3_1_2 {
	if x != nil {
		return x.GetOrderResponse_3_1_2
	}
	return nil
}

func (x *GetOrderResponse_3_1) GetGetOrderResponse_3_1_6() *GetOrderResponse_3_1_6 {
	if x != nil {
		return x.GetOrderResponse_3_1_6
	}
	return nil
}

func (x *GetOrderResponse_3_1) GetGetOrderResponse_3_1_15() *GetOrderResponse_3_1_15 {
	if x != nil {
		return x.GetOrderResponse_3_1_15
	}
	return nil
}

type GetOrderResponse_3_1_2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_2_3 *GetOrderResponse_3_1_2_3 `protobuf:"bytes,3,opt,name=GetOrderResponse_3_1_2_3,json=GetOrderResponse3123" json:"GetOrderResponse_3_1_2_3,omitempty"`
}

func (x *GetOrderResponse_3_1_2) Reset() {
	*x = GetOrderResponse_3_1_2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_2) ProtoMessage() {}

func (x *GetOrderResponse_3_1_2) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_2.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_2) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderResponse_3_1_2) GetGetOrderResponse_3_1_2_3() *GetOrderResponse_3_1_2_3 {
	if x != nil {
		return x.GetOrderResponse_3_1_2_3
	}
	return nil
}

type GetOrderResponse_3_1_2_3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_2_3_4 *GetOrderResponse_3_1_2_3_4 `protobuf:"bytes,4,opt,name=GetOrderResponse_3_1_2_3_4,json=GetOrderResponse31234" json:"GetOrderResponse_3_1_2_3_4,omitempty"`
}

func (x *GetOrderResponse_3_1_2_3) Reset() {
	*x = GetOrderResponse_3_1_2_3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_2_3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_2_3) ProtoMessage() {}

func (x *GetOrderResponse_3_1_2_3) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_2_3.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_2_3) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderResponse_3_1_2_3) GetGetOrderResponse_3_1_2_3_4() *GetOrderResponse_3_1_2_3_4 {
	if x != nil {
		return x.GetOrderResponse_3_1_2_3_4
	}
	return nil
}

type GetOrderResponse_3_1_2_3_4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *string `protobuf:"bytes,2,opt,name=Status" json:"Status,omitempty"`
}

func (x *GetOrderResponse_3_1_2_3_4) Reset() {
	*x = GetOrderResponse_3_1_2_3_4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_2_3_4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_2_3_4) ProtoMessage() {}

func (x *GetOrderResponse_3_1_2_3_4) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_2_3_4.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_2_3_4) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderResponse_3_1_2_3_4) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetOrderResponse_3_1_15 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_15_1 *GetOrderResponse_3_1_15_1 `protobuf:"bytes,1,opt,name=GetOrderResponse_3_1_15_1,json=GetOrderResponse31151" json:"GetOrderResponse_3_1_15_1,omitempty"`
	GetOrderResponse_3_1_15_2 *GetOrderResponse_3_1_15_2 `protobuf:"bytes,2,opt,name=GetOrderResponse_3_1_15_2,json=GetOrderResponse31152" json:"GetOrderResponse_3_1_15_2,omitempty"`
	GetOrderResponse_3_1_15_3 *GetOrderResponse_3_1_15_3 `protobuf:"bytes,3,opt,name=GetOrderResponse_3_1_15_3,json=GetOrderResponse31153" json:"GetOrderResponse_3_1_15_3,omitempty"`
}

func (x *GetOrderResponse_3_1_15) Reset() {
	*x = GetOrderResponse_3_1_15{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderResponse_3_1_15) GetGetOrderResponse_3_1_15_1() *GetOrderResponse_3_1_15_1 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_1
	}
	return nil
}

func (x *GetOrderResponse_3_1_15) GetGetOrderResponse_3_1_15_2() *GetOrderResponse_3_1_15_2 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_2
	}
	return nil
}

func (x *GetOrderResponse_3_1_15) GetGetOrderResponse_3_1_15_3() *GetOrderResponse_3_1_15_3 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_3
	}
	return nil
}

type GetOrderResponse_3_1_15_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_15_1_1 *GetOrderResponse_3_1_15_1_1 `protobuf:"bytes,1,opt,name=GetOrderResponse_3_1_15_1_1,json=GetOrderResponse311511" json:"GetOrderResponse_3_1_15_1_1,omitempty"`
}

func (x *GetOrderResponse_3_1_15_1) Reset() {
	*x = GetOrderResponse_3_1_15_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_1) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_1.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderResponse_3_1_15_1) GetGetOrderResponse_3_1_15_1_1() *GetOrderResponse_3_1_15_1_1 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_1_1
	}
	return nil
}

type GetOrderResponse_3_1_15_1_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantName *string `protobuf:"bytes,3,opt,name=MerchantName" json:"MerchantName,omitempty"`
}

func (x *GetOrderResponse_3_1_15_1_1) Reset() {
	*x = GetOrderResponse_3_1_15_1_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_1_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_1_1) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_1_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_1_1.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_1_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{15}
}

func (x *GetOrderResponse_3_1_15_1_1) GetMerchantName() string {
	if x != nil && x.MerchantName != nil {
		return *x.MerchantName
	}
	return ""
}

type GetOrderResponse_3_1_15_2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_15_2_2 *GetOrderResponse_3_1_15_2_2 `protobuf:"bytes,2,opt,name=GetOrderResponse_3_1_15_2_2,json=GetOrderResponse311522" json:"GetOrderResponse_3_1_15_2_2,omitempty"`
}

func (x *GetOrderResponse_3_1_15_2) Reset() {
	*x = GetOrderResponse_3_1_15_2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_2) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_2) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_2.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_2) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderResponse_3_1_15_2) GetGetOrderResponse_3_1_15_2_2() *GetOrderResponse_3_1_15_2_2 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_2_2
	}
	return nil
}

type GetOrderResponse_3_1_15_2_2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_15_2_2_1 *GetOrderResponse_3_1_15_2_2_1 `protobuf:"bytes,1,opt,name=GetOrderResponse_3_1_15_2_2_1,json=GetOrderResponse3115221" json:"GetOrderResponse_3_1_15_2_2_1,omitempty"`
}

func (x *GetOrderResponse_3_1_15_2_2) Reset() {
	*x = GetOrderResponse_3_1_15_2_2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_2_2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_2_2) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_2_2) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_2_2.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_2_2) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{17}
}

func (x *GetOrderResponse_3_1_15_2_2) GetGetOrderResponse_3_1_15_2_2_1() *GetOrderResponse_3_1_15_2_2_1 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_2_2_1
	}
	return nil
}

type GetOrderResponse_3_1_15_2_2_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Money *string `protobuf:"bytes,3,opt,name=Money" json:"Money,omitempty"`
}

func (x *GetOrderResponse_3_1_15_2_2_1) Reset() {
	*x = GetOrderResponse_3_1_15_2_2_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_2_2_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_2_2_1) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_2_2_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_2_2_1.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_2_2_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{18}
}

func (x *GetOrderResponse_3_1_15_2_2_1) GetMoney() string {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return ""
}

type GetOrderResponse_3_1_15_3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_15_3_2 *GetOrderResponse_3_1_15_3_2 `protobuf:"bytes,2,opt,name=GetOrderResponse_3_1_15_3_2,json=GetOrderResponse311532" json:"GetOrderResponse_3_1_15_3_2,omitempty"`
}

func (x *GetOrderResponse_3_1_15_3) Reset() {
	*x = GetOrderResponse_3_1_15_3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_3) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_3) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_3.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_3) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{19}
}

func (x *GetOrderResponse_3_1_15_3) GetGetOrderResponse_3_1_15_3_2() *GetOrderResponse_3_1_15_3_2 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_3_2
	}
	return nil
}

type GetOrderResponse_3_1_15_3_2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_15_3_2_4 *GetOrderResponse_3_1_15_3_2_4 `protobuf:"bytes,4,opt,name=GetOrderResponse_3_1_15_3_2_4,json=GetOrderResponse3115324" json:"GetOrderResponse_3_1_15_3_2_4,omitempty"`
}

func (x *GetOrderResponse_3_1_15_3_2) Reset() {
	*x = GetOrderResponse_3_1_15_3_2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_3_2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_3_2) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_3_2) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_3_2.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_3_2) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{20}
}

func (x *GetOrderResponse_3_1_15_3_2) GetGetOrderResponse_3_1_15_3_2_4() *GetOrderResponse_3_1_15_3_2_4 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_3_2_4
	}
	return nil
}

type GetOrderResponse_3_1_15_3_2_4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GetOrderResponse_3_1_15_3_2_4_1 *GetOrderResponse_3_1_15_3_2_4_1 `protobuf:"bytes,1,opt,name=GetOrderResponse_3_1_15_3_2_4_1,json=GetOrderResponse31153241" json:"GetOrderResponse_3_1_15_3_2_4_1,omitempty"`
}

func (x *GetOrderResponse_3_1_15_3_2_4) Reset() {
	*x = GetOrderResponse_3_1_15_3_2_4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_3_2_4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_3_2_4) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_3_2_4) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_3_2_4.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_3_2_4) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{21}
}

func (x *GetOrderResponse_3_1_15_3_2_4) GetGetOrderResponse_3_1_15_3_2_4_1() *GetOrderResponse_3_1_15_3_2_4_1 {
	if x != nil {
		return x.GetOrderResponse_3_1_15_3_2_4_1
	}
	return nil
}

type GetOrderResponse_3_1_15_3_2_4_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Merchant *string `protobuf:"bytes,3,opt,name=Merchant" json:"Merchant,omitempty"`
}

func (x *GetOrderResponse_3_1_15_3_2_4_1) Reset() {
	*x = GetOrderResponse_3_1_15_3_2_4_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_15_3_2_4_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_15_3_2_4_1) ProtoMessage() {}

func (x *GetOrderResponse_3_1_15_3_2_4_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_15_3_2_4_1.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_15_3_2_4_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{22}
}

func (x *GetOrderResponse_3_1_15_3_2_4_1) GetMerchant() string {
	if x != nil && x.Merchant != nil {
		return *x.Merchant
	}
	return ""
}

type GetOrderResponse_3_1_6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqKey *string `protobuf:"bytes,1,opt,name=ReqKey" json:"ReqKey,omitempty"`
}

func (x *GetOrderResponse_3_1_6) Reset() {
	*x = GetOrderResponse_3_1_6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderResponse_3_1_6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse_3_1_6) ProtoMessage() {}

func (x *GetOrderResponse_3_1_6) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse_3_1_6.ProtoReflect.Descriptor instead.
func (*GetOrderResponse_3_1_6) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{23}
}

func (x *GetOrderResponse_3_1_6) GetReqKey() string {
	if x != nil && x.ReqKey != nil {
		return *x.ReqKey
	}
	return ""
}

type Toysf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,opt,name=BaseRequest" json:"BaseRequest,omitempty"`
	Toysf_2     *uint64      `protobuf:"varint,2,opt,name=Toysf_2,json=Toysf2" json:"Toysf_2,omitempty"`
	Toysf_3     *string      `protobuf:"bytes,3,opt,name=Toysf_3,json=Toysf3" json:"Toysf_3,omitempty"`
	Toysf_4     *Toysf_4     `protobuf:"bytes,4,opt,name=Toysf_4,json=Toysf4" json:"Toysf_4,omitempty"`
}

func (x *Toysf) Reset() {
	*x = Toysf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toysf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toysf) ProtoMessage() {}

func (x *Toysf) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toysf.ProtoReflect.Descriptor instead.
func (*Toysf) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{24}
}

func (x *Toysf) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *Toysf) GetToysf_2() uint64 {
	if x != nil && x.Toysf_2 != nil {
		return *x.Toysf_2
	}
	return 0
}

func (x *Toysf) GetToysf_3() string {
	if x != nil && x.Toysf_3 != nil {
		return *x.Toysf_3
	}
	return ""
}

func (x *Toysf) GetToysf_4() *Toysf_4 {
	if x != nil {
		return x.Toysf_4
	}
	return nil
}

type Toysf_4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toysf_4_1 *Toysf_4_1 `protobuf:"bytes,1,opt,name=Toysf_4_1,json=Toysf41" json:"Toysf_4_1,omitempty"`
	Toysf_4_2 *string    `protobuf:"bytes,2,opt,name=Toysf_4_2,json=Toysf42" json:"Toysf_4_2,omitempty"`
	Toysf_4_3 *uint64    `protobuf:"varint,3,opt,name=Toysf_4_3,json=Toysf43" json:"Toysf_4_3,omitempty"`
}

func (x *Toysf_4) Reset() {
	*x = Toysf_4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toysf_4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toysf_4) ProtoMessage() {}

func (x *Toysf_4) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toysf_4.ProtoReflect.Descriptor instead.
func (*Toysf_4) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{25}
}

func (x *Toysf_4) GetToysf_4_1() *Toysf_4_1 {
	if x != nil {
		return x.Toysf_4_1
	}
	return nil
}

func (x *Toysf_4) GetToysf_4_2() string {
	if x != nil && x.Toysf_4_2 != nil {
		return *x.Toysf_4_2
	}
	return ""
}

func (x *Toysf_4) GetToysf_4_3() uint64 {
	if x != nil && x.Toysf_4_3 != nil {
		return *x.Toysf_4_3
	}
	return 0
}

type Toysf_4_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseRequest *BaseRequest `protobuf:"bytes,1,opt,name=BaseRequest" json:"BaseRequest,omitempty"`
	Toysf_4_1_2 *Toysf_4_1_2 `protobuf:"bytes,2,opt,name=Toysf_4_1_2,json=Toysf412" json:"Toysf_4_1_2,omitempty"`
	Key         *string      `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (x *Toysf_4_1) Reset() {
	*x = Toysf_4_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toysf_4_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toysf_4_1) ProtoMessage() {}

func (x *Toysf_4_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toysf_4_1.ProtoReflect.Descriptor instead.
func (*Toysf_4_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{26}
}

func (x *Toysf_4_1) GetBaseRequest() *BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *Toysf_4_1) GetToysf_4_1_2() *Toysf_4_1_2 {
	if x != nil {
		return x.Toysf_4_1_2
	}
	return nil
}

func (x *Toysf_4_1) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

type Toysf_4_1_2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID1         *string `protobuf:"bytes,1,opt,name=UUID1" json:"UUID1,omitempty"`
	Toysf_4_1_2_2 *uint64 `protobuf:"varint,2,opt,name=Toysf_4_1_2_2,json=Toysf4122" json:"Toysf_4_1_2_2,omitempty"`
	UUID2         *string `protobuf:"bytes,7,opt,name=UUID2" json:"UUID2,omitempty"`
}

func (x *Toysf_4_1_2) Reset() {
	*x = Toysf_4_1_2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toysf_4_1_2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toysf_4_1_2) ProtoMessage() {}

func (x *Toysf_4_1_2) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toysf_4_1_2.ProtoReflect.Descriptor instead.
func (*Toysf_4_1_2) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{27}
}

func (x *Toysf_4_1_2) GetUUID1() string {
	if x != nil && x.UUID1 != nil {
		return *x.UUID1
	}
	return ""
}

func (x *Toysf_4_1_2) GetToysf_4_1_2_2() uint64 {
	if x != nil && x.Toysf_4_1_2_2 != nil {
		return *x.Toysf_4_1_2_2
	}
	return 0
}

func (x *Toysf_4_1_2) GetUUID2() string {
	if x != nil && x.UUID2 != nil {
		return *x.UUID2
	}
	return ""
}

type ToysfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResponse    *BaseResponse    `protobuf:"bytes,1,opt,name=BaseResponse" json:"BaseResponse,omitempty"`
	ToysfResponse_3 *ToysfResponse_3 `protobuf:"bytes,3,opt,name=ToysfResponse_3,json=ToysfResponse3" json:"ToysfResponse_3,omitempty"`
}

func (x *ToysfResponse) Reset() {
	*x = ToysfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToysfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToysfResponse) ProtoMessage() {}

func (x *ToysfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToysfResponse.ProtoReflect.Descriptor instead.
func (*ToysfResponse) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{28}
}

func (x *ToysfResponse) GetBaseResponse() *BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *ToysfResponse) GetToysfResponse_3() *ToysfResponse_3 {
	if x != nil {
		return x.ToysfResponse_3
	}
	return nil
}

type ToysfResponse_3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToysfResponse_3_1 *ToysfResponse_3_1 `protobuf:"bytes,1,opt,name=ToysfResponse_3_1,json=ToysfResponse31" json:"ToysfResponse_3_1,omitempty"`
}

func (x *ToysfResponse_3) Reset() {
	*x = ToysfResponse_3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToysfResponse_3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToysfResponse_3) ProtoMessage() {}

func (x *ToysfResponse_3) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToysfResponse_3.ProtoReflect.Descriptor instead.
func (*ToysfResponse_3) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{29}
}

func (x *ToysfResponse_3) GetToysfResponse_3_1() *ToysfResponse_3_1 {
	if x != nil {
		return x.ToysfResponse_3_1
	}
	return nil
}

type ToysfResponse_3_1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tn *string `protobuf:"bytes,3,opt,name=Tn" json:"Tn,omitempty"`
}

func (x *ToysfResponse_3_1) Reset() {
	*x = ToysfResponse_3_1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payparams_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToysfResponse_3_1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToysfResponse_3_1) ProtoMessage() {}

func (x *ToysfResponse_3_1) ProtoReflect() protoreflect.Message {
	mi := &file_payparams_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToysfResponse_3_1.ProtoReflect.Descriptor instead.
func (*ToysfResponse_3_1) Descriptor() ([]byte, []int) {
	return file_payparams_proto_rawDescGZIP(), []int{30}
}

func (x *ToysfResponse_3_1) GetTn() string {
	if x != nil && x.Tn != nil {
		return *x.Tn
	}
	return ""
}

var File_payparams_proto protoreflect.FileDescriptor

var file_payparams_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x61, 0x79, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6d, 0x6d, 0x32, 0x22, 0xb7, 0x01, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65,
	0x22, 0x28, 0x0a, 0x10, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x54, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4f, 0x0a, 0x0c, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x2d, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x6d, 0x32, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x54, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x85, 0x01, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x6d, 0x32, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x0b, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x6d, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x6d, 0x70, 0x32,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x6d, 0x70, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x6d, 0x70, 0x33, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x6d, 0x70, 0x34, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x54, 0x6d, 0x70, 0x34, 0x52, 0x04, 0x74,
	0x6d, 0x70, 0x34, 0x22, 0x58, 0x0a, 0x04, 0x54, 0x6d, 0x70, 0x34, 0x12, 0x22, 0x0a, 0x06, 0x54,
	0x6d, 0x70, 0x34, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6d,
	0x32, 0x2e, 0x54, 0x6d, 0x70, 0x34, 0x5f, 0x31, 0x52, 0x05, 0x54, 0x6d, 0x70, 0x34, 0x31, 0x12,
	0x15, 0x0a, 0x06, 0x74, 0x6d, 0x70, 0x34, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6d, 0x70, 0x34, 0x32, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6d, 0x70, 0x34, 0x5f, 0x33,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6d, 0x70, 0x34, 0x33, 0x22, 0x6a, 0x0a,
	0x06, 0x54, 0x6d, 0x70, 0x34, 0x5f, 0x31, 0x12, 0x32, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x6d, 0x32, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x70,
	0x61, 0x79, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x50, 0x61, 0x79, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x09,
	0x70, 0x61, 0x79, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x09, 0x50, 0x61,
	0x79, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x5f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x52, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x22, 0x61, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x33, 0x12, 0x4b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x52, 0x12, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x22,
	0x8f, 0x02, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x12, 0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31,
	0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x33, 0x5f, 0x31, 0x5f, 0x32, 0x52, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x32, 0x12, 0x50, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33,
	0x5f, 0x31, 0x5f, 0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6d, 0x32,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x36, 0x52, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x36, 0x12, 0x53, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x52, 0x14, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x31,
	0x35, 0x22, 0x6f, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x32, 0x12, 0x55, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x33, 0x5f, 0x31, 0x5f, 0x32, 0x5f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x32, 0x5f, 0x33, 0x52, 0x14, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31,
	0x32, 0x33, 0x22, 0x76, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x32, 0x5f, 0x33, 0x12, 0x5a,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x32, 0x5f, 0x33, 0x5f, 0x34, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x32, 0x5f,
	0x33, 0x5f, 0x34, 0x52, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x32, 0x33, 0x34, 0x22, 0x34, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33,
	0x5f, 0x31, 0x5f, 0x32, 0x5f, 0x33, 0x5f, 0x34, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0xa7, 0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x12, 0x58, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x31, 0x52,
	0x15, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x33, 0x31, 0x31, 0x35, 0x31, 0x12, 0x58, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31,
	0x35, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x6d, 0x32, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x32, 0x52, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x31, 0x35, 0x32,
	0x12, 0x58, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31,
	0x35, 0x5f, 0x33, 0x52, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x31, 0x35, 0x33, 0x22, 0x7a, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33,
	0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x31, 0x12, 0x5d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f,
	0x31, 0x35, 0x5f, 0x31, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d,
	0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x31, 0x5f, 0x31, 0x52, 0x16,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x33, 0x31, 0x31, 0x35, 0x31, 0x31, 0x22, 0x41, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31,
	0x35, 0x5f, 0x31, 0x5f, 0x31, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7a, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f,
	0x31, 0x5f, 0x31, 0x35, 0x5f, 0x32, 0x12, 0x5d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31,
	0x35, 0x5f, 0x32, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x6d,
	0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x32, 0x5f, 0x32, 0x52, 0x16, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33,
	0x31, 0x31, 0x35, 0x32, 0x32, 0x22, 0x81, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31,
	0x35, 0x5f, 0x32, 0x5f, 0x32, 0x12, 0x62, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35,
	0x5f, 0x32, 0x5f, 0x32, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d,
	0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x32, 0x5f, 0x32, 0x5f, 0x31,
	0x52, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x33, 0x31, 0x31, 0x35, 0x32, 0x32, 0x31, 0x22, 0x35, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f,
	0x31, 0x5f, 0x31, 0x35, 0x5f, 0x32, 0x5f, 0x32, 0x5f, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x22, 0x7a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x12, 0x5d, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35,
	0x5f, 0x33, 0x5f, 0x32, 0x52, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x31, 0x35, 0x33, 0x32, 0x22, 0x81, 0x01, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x5f, 0x32, 0x12, 0x62, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x5f, 0x32, 0x5f, 0x34, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31,
	0x35, 0x5f, 0x33, 0x5f, 0x32, 0x5f, 0x34, 0x52, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x31, 0x31, 0x35, 0x33, 0x32, 0x34,
	0x22, 0x88, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x5f, 0x32,
	0x5f, 0x34, 0x12, 0x67, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x5f,
	0x32, 0x5f, 0x34, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x6d,
	0x32, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x5f, 0x32, 0x5f, 0x34, 0x5f,
	0x31, 0x52, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x33, 0x31, 0x31, 0x35, 0x33, 0x32, 0x34, 0x31, 0x22, 0x3d, 0x0a, 0x1f, 0x47,
	0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x33, 0x5f, 0x31, 0x5f, 0x31, 0x35, 0x5f, 0x33, 0x5f, 0x32, 0x5f, 0x34, 0x5f, 0x31, 0x12, 0x1a,
	0x0a, 0x08, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33,
	0x5f, 0x31, 0x5f, 0x36, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x71, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x71, 0x4b, 0x65, 0x79, 0x22, 0x94, 0x01, 0x0a,
	0x05, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x12, 0x32, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6d,
	0x32, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x54, 0x6f,
	0x79, 0x73, 0x66, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x54, 0x6f, 0x79,
	0x73, 0x66, 0x32, 0x12, 0x17, 0x0a, 0x07, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x33, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x33, 0x12, 0x25, 0x0a, 0x07,
	0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6d, 0x6d, 0x32, 0x2e, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x52, 0x06, 0x54, 0x6f, 0x79,
	0x73, 0x66, 0x34, 0x22, 0x6d, 0x0a, 0x07, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x12, 0x2a,
	0x0a, 0x09, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x5f,
	0x31, 0x52, 0x07, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x34, 0x31, 0x12, 0x1a, 0x0a, 0x09, 0x54, 0x6f,
	0x79, 0x73, 0x66, 0x5f, 0x34, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54,
	0x6f, 0x79, 0x73, 0x66, 0x34, 0x32, 0x12, 0x1a, 0x0a, 0x09, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f,
	0x34, 0x5f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x54, 0x6f, 0x79, 0x73, 0x66,
	0x34, 0x33, 0x22, 0x82, 0x01, 0x0a, 0x09, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x5f, 0x31,
	0x12, 0x32, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x0b, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x5f,
	0x31, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6d, 0x32, 0x2e,
	0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x5f, 0x31, 0x5f, 0x32, 0x52, 0x08, 0x54, 0x6f, 0x79,
	0x73, 0x66, 0x34, 0x31, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x5b, 0x0a, 0x0b, 0x54, 0x6f, 0x79, 0x73, 0x66,
	0x5f, 0x34, 0x5f, 0x31, 0x5f, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x55, 0x49, 0x44, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x55, 0x55, 0x49, 0x44, 0x31, 0x12, 0x20, 0x0a, 0x0d,
	0x54, 0x6f, 0x79, 0x73, 0x66, 0x5f, 0x34, 0x5f, 0x31, 0x5f, 0x32, 0x5f, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x34, 0x31, 0x32, 0x32, 0x12, 0x14,
	0x0a, 0x05, 0x55, 0x55, 0x49, 0x44, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x55,
	0x55, 0x49, 0x44, 0x32, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x6d, 0x32, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a,
	0x0f, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6d, 0x32, 0x2e, 0x54, 0x6f, 0x79,
	0x73, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x52, 0x0e, 0x54, 0x6f,
	0x79, 0x73, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33, 0x22, 0x55, 0x0a, 0x0f,
	0x54, 0x6f, 0x79, 0x73, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x12,
	0x42, 0x0a, 0x11, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x33, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6d, 0x32,
	0x2e, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33,
	0x5f, 0x31, 0x52, 0x0f, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x33, 0x31, 0x22, 0x23, 0x0a, 0x11, 0x54, 0x6f, 0x79, 0x73, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x33, 0x5f, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6e, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x6d, 0x32,
}

var (
	file_payparams_proto_rawDescOnce sync.Once
	file_payparams_proto_rawDescData = file_payparams_proto_rawDesc
)

func file_payparams_proto_rawDescGZIP() []byte {
	file_payparams_proto_rawDescOnce.Do(func() {
		file_payparams_proto_rawDescData = protoimpl.X.CompressGZIP(file_payparams_proto_rawDescData)
	})
	return file_payparams_proto_rawDescData
}

var file_payparams_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_payparams_proto_goTypes = []interface{}{
	(*BaseRequest)(nil),                     // 0: mm2.BaseRequest
	(*SKBuiltinStringT)(nil),                // 1: mm2.SKBuiltinStringT
	(*BaseResponse)(nil),                    // 2: mm2.BaseResponse
	(*GetOrder)(nil),                        // 3: mm2.GetOrder
	(*Tmp4)(nil),                            // 4: mm2.Tmp4
	(*Tmp4_1)(nil),                          // 5: mm2.Tmp4_1
	(*Payparams)(nil),                       // 6: mm2.Payparams
	(*GetOrderResponse)(nil),                // 7: mm2.GetOrderResponse
	(*GetOrderResponse_3)(nil),              // 8: mm2.GetOrderResponse_3
	(*GetOrderResponse_3_1)(nil),            // 9: mm2.GetOrderResponse_3_1
	(*GetOrderResponse_3_1_2)(nil),          // 10: mm2.GetOrderResponse_3_1_2
	(*GetOrderResponse_3_1_2_3)(nil),        // 11: mm2.GetOrderResponse_3_1_2_3
	(*GetOrderResponse_3_1_2_3_4)(nil),      // 12: mm2.GetOrderResponse_3_1_2_3_4
	(*GetOrderResponse_3_1_15)(nil),         // 13: mm2.GetOrderResponse_3_1_15
	(*GetOrderResponse_3_1_15_1)(nil),       // 14: mm2.GetOrderResponse_3_1_15_1
	(*GetOrderResponse_3_1_15_1_1)(nil),     // 15: mm2.GetOrderResponse_3_1_15_1_1
	(*GetOrderResponse_3_1_15_2)(nil),       // 16: mm2.GetOrderResponse_3_1_15_2
	(*GetOrderResponse_3_1_15_2_2)(nil),     // 17: mm2.GetOrderResponse_3_1_15_2_2
	(*GetOrderResponse_3_1_15_2_2_1)(nil),   // 18: mm2.GetOrderResponse_3_1_15_2_2_1
	(*GetOrderResponse_3_1_15_3)(nil),       // 19: mm2.GetOrderResponse_3_1_15_3
	(*GetOrderResponse_3_1_15_3_2)(nil),     // 20: mm2.GetOrderResponse_3_1_15_3_2
	(*GetOrderResponse_3_1_15_3_2_4)(nil),   // 21: mm2.GetOrderResponse_3_1_15_3_2_4
	(*GetOrderResponse_3_1_15_3_2_4_1)(nil), // 22: mm2.GetOrderResponse_3_1_15_3_2_4_1
	(*GetOrderResponse_3_1_6)(nil),          // 23: mm2.GetOrderResponse_3_1_6
	(*Toysf)(nil),                           // 24: mm2.Toysf
	(*Toysf_4)(nil),                         // 25: mm2.Toysf_4
	(*Toysf_4_1)(nil),                       // 26: mm2.Toysf_4_1
	(*Toysf_4_1_2)(nil),                     // 27: mm2.Toysf_4_1_2
	(*ToysfResponse)(nil),                   // 28: mm2.ToysfResponse
	(*ToysfResponse_3)(nil),                 // 29: mm2.ToysfResponse_3
	(*ToysfResponse_3_1)(nil),               // 30: mm2.ToysfResponse_3_1
}
var file_payparams_proto_depIdxs = []int32{
	1,  // 0: mm2.BaseResponse.errMsg:type_name -> mm2.SKBuiltinStringT
	0,  // 1: mm2.GetOrder.BaseRequest:type_name -> mm2.BaseRequest
	4,  // 2: mm2.GetOrder.tmp4:type_name -> mm2.Tmp4
	5,  // 3: mm2.Tmp4.Tmp4_1:type_name -> mm2.Tmp4_1
	0,  // 4: mm2.Tmp4_1.BaseRequest:type_name -> mm2.BaseRequest
	6,  // 5: mm2.Tmp4_1.payparams:type_name -> mm2.Payparams
	2,  // 6: mm2.GetOrderResponse.BaseResponse:type_name -> mm2.BaseResponse
	8,  // 7: mm2.GetOrderResponse.GetOrderResponse_3:type_name -> mm2.GetOrderResponse_3
	9,  // 8: mm2.GetOrderResponse_3.GetOrderResponse_3_1:type_name -> mm2.GetOrderResponse_3_1
	10, // 9: mm2.GetOrderResponse_3_1.GetOrderResponse_3_1_2:type_name -> mm2.GetOrderResponse_3_1_2
	23, // 10: mm2.GetOrderResponse_3_1.GetOrderResponse_3_1_6:type_name -> mm2.GetOrderResponse_3_1_6
	13, // 11: mm2.GetOrderResponse_3_1.GetOrderResponse_3_1_15:type_name -> mm2.GetOrderResponse_3_1_15
	11, // 12: mm2.GetOrderResponse_3_1_2.GetOrderResponse_3_1_2_3:type_name -> mm2.GetOrderResponse_3_1_2_3
	12, // 13: mm2.GetOrderResponse_3_1_2_3.GetOrderResponse_3_1_2_3_4:type_name -> mm2.GetOrderResponse_3_1_2_3_4
	14, // 14: mm2.GetOrderResponse_3_1_15.GetOrderResponse_3_1_15_1:type_name -> mm2.GetOrderResponse_3_1_15_1
	16, // 15: mm2.GetOrderResponse_3_1_15.GetOrderResponse_3_1_15_2:type_name -> mm2.GetOrderResponse_3_1_15_2
	19, // 16: mm2.GetOrderResponse_3_1_15.GetOrderResponse_3_1_15_3:type_name -> mm2.GetOrderResponse_3_1_15_3
	15, // 17: mm2.GetOrderResponse_3_1_15_1.GetOrderResponse_3_1_15_1_1:type_name -> mm2.GetOrderResponse_3_1_15_1_1
	17, // 18: mm2.GetOrderResponse_3_1_15_2.GetOrderResponse_3_1_15_2_2:type_name -> mm2.GetOrderResponse_3_1_15_2_2
	18, // 19: mm2.GetOrderResponse_3_1_15_2_2.GetOrderResponse_3_1_15_2_2_1:type_name -> mm2.GetOrderResponse_3_1_15_2_2_1
	20, // 20: mm2.GetOrderResponse_3_1_15_3.GetOrderResponse_3_1_15_3_2:type_name -> mm2.GetOrderResponse_3_1_15_3_2
	21, // 21: mm2.GetOrderResponse_3_1_15_3_2.GetOrderResponse_3_1_15_3_2_4:type_name -> mm2.GetOrderResponse_3_1_15_3_2_4
	22, // 22: mm2.GetOrderResponse_3_1_15_3_2_4.GetOrderResponse_3_1_15_3_2_4_1:type_name -> mm2.GetOrderResponse_3_1_15_3_2_4_1
	0,  // 23: mm2.Toysf.BaseRequest:type_name -> mm2.BaseRequest
	25, // 24: mm2.Toysf.Toysf_4:type_name -> mm2.Toysf_4
	26, // 25: mm2.Toysf_4.Toysf_4_1:type_name -> mm2.Toysf_4_1
	0,  // 26: mm2.Toysf_4_1.BaseRequest:type_name -> mm2.BaseRequest
	27, // 27: mm2.Toysf_4_1.Toysf_4_1_2:type_name -> mm2.Toysf_4_1_2
	2,  // 28: mm2.ToysfResponse.BaseResponse:type_name -> mm2.BaseResponse
	29, // 29: mm2.ToysfResponse.ToysfResponse_3:type_name -> mm2.ToysfResponse_3
	30, // 30: mm2.ToysfResponse_3.ToysfResponse_3_1:type_name -> mm2.ToysfResponse_3_1
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_payparams_proto_init() }
func file_payparams_proto_init() {
	if File_payparams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_payparams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKBuiltinStringT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tmp4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tmp4_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payparams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_2_3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_2_3_4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_1_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_2_2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_2_2_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_3_2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_3_2_4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_15_3_2_4_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderResponse_3_1_6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toysf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toysf_4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toysf_4_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toysf_4_1_2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToysfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToysfResponse_3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payparams_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToysfResponse_3_1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payparams_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payparams_proto_goTypes,
		DependencyIndexes: file_payparams_proto_depIdxs,
		MessageInfos:      file_payparams_proto_msgTypes,
	}.Build()
	File_payparams_proto = out.File
	file_payparams_proto_rawDesc = nil
	file_payparams_proto_goTypes = nil
	file_payparams_proto_depIdxs = nil
}
